Repository eth-protocol-fellows/protocol-studies, pull requests merged in 2024-04, with the labels that each got.

#131 🚥 ci(Spell check): Github action
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/spell-check.yml
  docs/contributing.md
  docs/eps/nodes_workshop.md
  docs/eps/week2.md
  docs/eps/week6-dev.md
  docs/eps/week6-research.md
  docs/eps/week7-dev.md
  docs/readme.md
  docs/topics.md
  docs/wiki/EL/JSON-RPC.md
  docs/wiki/EL/block-production.md
  docs/wiki/protocol/data-structures.md
  docs/wiki/research/scaling/core-changes/eip-4844.md
  docs/wiki/research/scaling/scaling.md
  notes/Chloe_notes.md
  notes/gorondan.md
  wordlist.txt
Labels: enhancement

#203 BLS page in Cryptography section
  docs/images/elliptic-curves/bls-alice.png
  docs/images/elliptic-curves/bls-setup.svg
  docs/images/elliptic-curves/bls-signing.svg
  docs/images/elliptic-curves/bls-verifying.svg
  docs/wiki/Cryptography/bls.md
Labels: documentation

#211 Roadmap wiki page
  docs/wiki/research/img/full_roadmap2024_1600x1596.webp
  docs/wiki/research/roadmap.md
Labels: good first issue, looking-for-collaboration

#218 Cryptography/bls
  docs/_sidebar.md
  docs/images/elliptic-curves/bls-alice.png
  docs/images/elliptic-curves/bls-key.svg
  docs/images/elliptic-curves/bls-setup.svg
  docs/images/elliptic-curves/bls-signing.svg
  docs/images/elliptic-curves/bls-verifying.svg
  docs/wiki/CL/cl-clients.md
  docs/wiki/Cryptography/bls.md
  wordlist.txt
Labels: documentation
